from __future__ import annotations

from pathlib import Path

from .errors import SecurityPolicyError


GENERATED_MARKER = "<!-- Generated by Codebase Architect. Manual edits may be overwritten. -->"


def resolve_output_path(repository: Path, configured: str, *, allow_absolute_outside: bool = False) -> Path:
    root = repository.resolve()
    raw = Path(configured)
    if raw.is_absolute():
        candidate = raw.resolve()
        if not allow_absolute_outside:
            try:
                candidate.relative_to(root)
            except ValueError as exc:
                raise SecurityPolicyError(f"Absolute output path escapes repository: {configured}") from exc
        _reject_symlink_chain(root, candidate)
        return candidate
    candidate = (repository / raw).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise SecurityPolicyError(f"Relative output path escapes repository: {configured}") from exc
    _reject_symlink_chain(root, candidate)
    return candidate


def write_generated(path: Path, content: str, *, marker: str = GENERATED_MARKER, force: bool = False) -> Path:
    _reject_existing_symlink(path)
    for parent in path.parents:
        if parent.exists():
            _reject_existing_symlink(parent)
            break
    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8", errors="replace")
        if marker not in existing:
            raise SecurityPolicyError(f"Refusing to overwrite non-generated file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    temp.write_text(content, encoding="utf-8")
    temp.replace(path)
    return path


def _reject_symlink_chain(root: Path, candidate: Path) -> None:
    try:
        relative = candidate.relative_to(root)
    except ValueError:
        relative = Path(candidate.name)
    current = root
    _reject_existing_symlink(current)
    for part in relative.parts:
        current = current / part
        if current.exists():
            _reject_existing_symlink(current)


def _reject_existing_symlink(path: Path) -> None:
    if path.is_symlink():
        raise SecurityPolicyError(f"Refusing to write through symlinked path: {path}")
