from __future__ import annotations

from pathlib import Path

from .errors import SecurityPolicyError


GENERATED_MARKER = "<!-- Generated by Codebase Architect. Manual edits may be overwritten. -->"


def resolve_output_path(repository: Path, configured: str) -> Path:
    raw = Path(configured)
    if raw.is_absolute():
        return raw.resolve()
    candidate = (repository / raw).resolve()
    try:
        candidate.relative_to(repository.resolve())
    except ValueError as exc:
        raise SecurityPolicyError(f"Relative output path escapes repository: {configured}") from exc
    return candidate


def write_generated(path: Path, content: str, *, marker: str = GENERATED_MARKER, force: bool = False) -> Path:
    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8", errors="replace")
        if marker not in existing:
            raise SecurityPolicyError(f"Refusing to overwrite non-generated file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    temp.write_text(content, encoding="utf-8")
    temp.replace(path)
    return path
