from __future__ import annotations
import json
from dataclasses import dataclass, field
from pathlib import Path
from .graph import CodeGraph
from .secret_filter import contains_secret

@dataclass(slots=True)
class ValidationReport:
    errors: list[str]=field(default_factory=list)
    warnings: list[str]=field(default_factory=list)
    @property
    def ok(self)->bool: return not self.errors
    def markdown(self)->str:
        errors="\n".join(f"- {x}" for x in self.errors) or "- None"
        warnings="\n".join(f"- {x}" for x in self.warnings) or "- None"
        return f"""<!-- Generated by Codebase Architect. Manual edits may be overwritten. -->
# Validation Report

## Status
{"PASS" if self.ok else "FAIL"}

## Errors
{errors}

## Warnings
{warnings}
"""

def validate_graph(graph:CodeGraph)->ValidationReport:
    report=ValidationReport()
    for edge in graph.edges.values():
        if edge.source not in graph.nodes: report.errors.append(f"Edge {edge.id} has missing source {edge.source}")
        if edge.target not in graph.nodes: report.errors.append(f"Edge {edge.id} has missing target {edge.target}")
        if edge.classification=="VERIFIED" and not edge.evidence: report.errors.append(f"Verified edge {edge.id} has no evidence")
    return report

def validate_output(output:Path)->ValidationReport:
    report=ValidationReport()
    for path in [output/"README.md",output/"DEEP_TECHNICAL_ARCHITECTURE.md",output/"evidence"/"code-intelligence-graph.json",output/"evidence"/"architecture.json"]:
        if not path.exists(): report.errors.append(f"Missing generated artifact: {path}")
    for path in output.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in {".md",".json",".mmd",".svg",".txt"}: continue
        try: content=path.read_text(encoding="utf-8",errors="replace")
        except OSError as exc: report.errors.append(f"Cannot read {path}: {exc}");continue
        if contains_secret(content): report.errors.append(f"Potential secret detected in generated output: {path}")
    graph_file=output/"evidence"/"code-intelligence-graph.json"
    if graph_file.exists():
        try:
            raw=json.loads(graph_file.read_text(encoding="utf-8"))
            if "nodes" not in raw or "edges" not in raw: report.errors.append("Graph JSON is missing nodes/edges")
        except json.JSONDecodeError as exc: report.errors.append(f"Graph JSON invalid: {exc}")
    return report
